spring:
  datasource:
    url: jdbc:mysql://118.24.1.170:3306/gak?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=UTC
    username: gak
    password: G&k123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      min-idle: 5
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      use-global-data-source-stat: true
      validation-query: select 'x'
      stat-view-servlet:
        enabled: true
        login-password: gak.123456789
        login-username: admin
        url-pattern: /druid/*
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      repositories:
        enabled: false
    rest:
      base-path: /rest
      default-page-size: 10
      default-media-type: application/json
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: lessonCloud@japoul.cn
    password: lessonC2019
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    test-connection: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
server:
  servlet:
    context-path: /api

application:
  security:
    enable: true
    client-id: gak
    client-secret: $2a$12$cLJL7vsJLzM07g83pV7FBeosMxwi0TWm1N70GskkmG2CIcWCFbLYK
    access-token-validity-hour: 24
    refresh-token-validity-hour: 24
  code:
    email-code-validity-minute: 30
    email-enable: false
  qiniu: # 七牛云配置
    area: 华南 # 可选值 华东 华南 华北 北美 东南亚 不填会自动判断
    access-key: MDRca19RDHiDgv3T677skHmPmzp8_gn8QahRQLFX
    secret-key: UKTf_UA7S3-Z7QP4kRUVraBP-eI_HsU2IfPjB5U0
    bucket: resource-pic
    domain: q0zlaui5t.bkt.clouddn.com
    dir-name: oneYard
    host: http://q0zlaui5t.bkt.clouddn.com/
logging:
  level:
    org.springframework.security: DEBUG
    in.gaks.oneyard: DEBUG
    org.springframework.context.support.[PostProcessorRegistrationDelegate$BeanPostProcessorChecker]: WARN
  file:
    path: logs