spring:
  datasource:
    url: jdbc:mysql://118.24.1.170:3306/gak?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=UTC
    username: gak
    password: G&k123456
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    rest:
      base-path: /rest
      default-page-size: 10
      default-media-type: application/json
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: lessonCloud@japoul.cn
    password: lessonC2019
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    test-connection: false
server:
  servlet:
    context-path: /api

application:
  security:
    enable: false
    client-id: gak
    client-secret: $2a$12$cLJL7vsJLzM07g83pV7FBeosMxwi0TWm1N70GskkmG2CIcWCFbLYK
    access-token-validity-hour: 24
    refresh-token-validity-hour: 24
  code:
    email-code-validity-minute: 30
    email-enable: false
logging:
  level:
    org:
      springframework:
        security: DEBUG