spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:10001/gak?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=UTC
    username: root
    password:
  mail:
    test-connection: false
  redis:
    password:
    port: 10002
  profiles: prod
application:
  security:
    enable: true
    client-id: gak
    client-secret: $2a$12$cLJL7vsJLzM07g83pV7FBeosMxwi0TWm1N70GskkmG2CIcWCFbLYK
    access-token-validity-hour: 24
    refresh-token-validity-hour: 72
  code:
    email-code-validity-minute: 15
    email-enable: true
server:
  port: 10011