spring:
  datasource:
    url: jdbc:mysql://118.24.1.170:3306/gak?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=UTC
    username: gak
    password: G&k123456
  jpa:
    show-sql: true
