spring:
  datasource:
    url: jdbc:mysql://118.24.1.170:3306/gak?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=UTC
    username: gak
    password: G&k123456
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
application:
  security:
    enable: true
    client-id: gak
    client-secret: $2a$12$cLJL7vsJLzM07g83pV7FBeosMxwi0TWm1N70GskkmG2CIcWCFbLYK
    access-token-validity-hour: 24
    refresh-token-validity-hour: 24
logging:
  level:
    org:
      springframework:
        security: DEBUG